version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: microcoin
      POSTGRES_USER: microcoin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U microcoin -d microcoin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  microcoin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://microcoin:password@postgres:5432/microcoin?sslmode=disable
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: make run

volumes:
  postgres_data:
  redis_data:
